#!/usr/bin/env bash

#
#  ██                    ██              ██  ██
#  ░░                    ░██             ░██ ░██
#   ██ ███████   ██████ ██████  ██████   ░██ ░██
#  ░██░░██░░░██ ██░░░░ ░░░██░  ░░░░░░██  ░██ ░██
#  ░██ ░██  ░██░░█████   ░██    ███████  ░██ ░██
#  ░██ ░██  ░██ ░░░░░██  ░██   ██░░░░██  ░██ ░██
#  ░██ ███  ░██ ██████   ░░██ ░░████████ ███ ███
#  ░░ ░░░   ░░ ░░░░░░     ░░   ░░░░░░░░ ░░░ ░░░
#

set -Eeuo pipefail

# All the files that will be symlinked to ~.
files_to_symlink="
.config/amfora
.config/bat
.config/gh
.config/htop
.config/youtube-dl
.gnupg/gpg.conf
.gnupg/gpg-agent.conf
.curlrc
.gitconfig
.gvimrc
.hushlogin
.npmrc
.nuxtrc
.vim
.vimrc
.zshrc"

# Symlink them up
for f in $files_to_symlink; do
	ln -nfsv "$HOME/dotfiles/$f" "$HOME/$f"
done
